port 26379
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor lab-primary primary 6379 1
sentinel down-after-milliseconds lab-primary 1500
sentinel failover-timeout lab-primary 10000
sentinel parallel-syncs lab-primary 1

